---
- name: Running a Webserver Workflow
  hosts: all
  become: true
  tasks: 

  - name: Installing Packages VSFTPD and Firewalld
    dnf: 
      name: "{{ item }}"
      state: latest
    loop: 
    - vsftpd
    - ftp
    - firewalld

  - name: Starting and Enabling Service HTTPD and Firewalld
    service: 
      name: "{{ item }}"
      state: started
      enabled: true
    loop: 
    - vsftpd
    - firewalld

  - name: Adding Web Service Port in Firewalld
    firewalld:
      service: ftp
      state: enabled
      immediate: true
      permanent: true

  handlers:

  - name: restart_webservice
    service: 
      name: httpd
      state: restarted
      enabled: true
...
